name: Run Tests and Publish Allure Report

on:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Allure CLI
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g allure-commandline

    - name: Run tests
      run: mvn clean test

    - name: Generate Allure report
      run: |
        mvn allure:report
        allure generate target/site/allure-maven-plugin -o allure-report --clean

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
